version: "3.9"

services:

  database:
    container_name: realestate_database
    image: postgres
    environment:
      - POSTGRES_USER=realestate
      - POSTGRES_PASSWORD=realestate_pass
      - POSTGRES_DB=realestate_db
    ports:
      - "5432:5432"
    user: 999:999
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: realestate_redis
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    container_name: realestate_app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis

volumes:
  pgdata:
