version: "3.9"

services:

  database:
    container_name: deno_test_database
    image: postgres
    environment:
      - POSTGRES_USER=deno_test
      - POSTGRES_PASSWORD=deno_test_pass
      - POSTGRES_DB=deno_test_db
    ports:
      - "5432:5432"
    user: 999:999
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: deno_test_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    # networks:
    #   - app-network

  app:
    container_name: deno_test_app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis

volumes:
  pgdata:
