CREATE TABLE IF NOT EXISTS listing_media (
    id SERIAL PRIMARY KEY NOT NULL,
    listing_id INT NOT NULL,
    alt_text VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);